### ISSUE TITLE
please fix docs license

### ISSUE THREAD

**Issue by onlyjob** [docker/spdystream#57]
> Docs released under Creative commons.

Is an improper grant of license. A license version should be mentioned in the proper format like "CC-BY-SA-4.0" with a link to the full text of the license ideally accompanied by full text of the license committed to repository.

Also it would be nice to mention scope of the license (i.e. which docs?).

Thanks.

**Comment by onlyjob** [comment]
Also this could be interpreted that `README.md` is under CC (any version?) while the rest of the _spdystream_  is unser Apache-2.0... Please clarify.

**Comment by onlyjob** [comment]
Any progress please?

**Comment by onlyjob** [comment]
Thanks! :)

**Comment by onlyjob** [comment]
Sorry for being pedantic but attribution is still a little bit ambiguous. It says "Code and documentation copyright..." and then it mention license only specifically to code: "Code released under the Apache 2.0 license.".

Perhaps it would be best to drop "Code" and "Code and documentation" so it reads at least

    Copyright 2013-2014 Docker, inc.
    Released under the Apache 2.0 license.

Please note that the text of the Apache-2.0 license itself (in the very end) recommends to use very specific text of license grant. If possible please consider applying Apache-2.0 license as per instructions in the license. Cheers.

**Comment by dmcgowan** [comment]
Not quite sure I understand the ambiguity. The statement is saying the code is covered by the Apache license and code and documentation (which currently there is none besides code documentation) are copyright. I am not an expert on any of these things and only following the language from other Docker repositories. If you notice inconsistencies between this project and others then I will gladly rectify. However if you find an issue with how we handle licensing in general, then it is probably something I would need to escalate. Normally I would just point to the https://github.com/docker/spdystream/blob/master/LICENSE from the Readme. If you find something lacking in the License that is a different story, if it is just the Readme then I will glady remove the existing language and just put "See LICENSE file".

**Comment by onlyjob** [comment]
Copyrighted materials without explicit license are non-free (i.e. "All Rights Reserved").
Technically speaking, current license grant makes non-code non-free (e.g. non distributable, not modifiable etc.). Please do not justify incorrect wording of license grant by proliferation of bad practice in the other repositories. FYI there were another bad case of license grant in https://github.com/docker/libkv/issues/50 as well as https://github.com/docker/swarm/issues/1280 so Docker repositories do not shine in that regards. IMHO it would be best to apply license properly, as the text of the license instruct, without unnecessary improvisations.
Thanks.

**Comment by dmcgowan** [comment]
Apparently this issue was already escalated and resolved in libkv. I followed what was used there which was vetted by individuals more knowledgeable than I am about licenses. Thank you for your concern. If you see any further inconsistencies feel free to open up a new issue.
