### ISSUE TITLE
Possible to send to closed channels

### ISSUE THREAD

**Issue by ncdc** [docker/spdystream#60]
The code currently uses this convention to try to avoid sending to a closed channel:

```go
select {
  case <-stream.closeChan:
    debugMessage("(%p) (%d) Data frame not sent (stream shut down)", stream, stream.streamId)
  case stream.dataChan <- frame.Data:
    debugMessage("(%p) (%d) Data frame sent", stream, stream.streamId)
}
```

Unfortunately, if multiple case statements can proceed, there is no guarantee that they a processed in the order they're written in the source code (see https://golang.org/ref/spec#Select_statements item 2 for more info). What this means is that it is possible for stream.closeChan to be closed, stream.dataChan to be closed, and the second case statement to be executed, resulting in a panic.

**Comment by ncdc** [comment]
cc @smarterclayton @liggitt

**Comment by dmcgowan** [comment]
We need to provide a different way to synchronize this then, likely ensuring that the `dataChan` can only be closed after `closeChan` and handling of that closure has been acknowledged. I will work on something for this since I have this same pattern in my streams library https://github.com/dmcgowan/streams/blob/master/spdy/spdy.go#L95.

**Comment by dmcgowan** [comment]
Actually, after reviewing further, I don't think it is necessary to close the `stream.dataChan` at all. This line can just be removed https://github.com/docker/spdystream/blob/master/stream.go#L325. The channel can be garbage collected with the stream, the closeChan provides all the necessary signaling to ensure nothing is blocking on that channel.

**Comment by ncdc** [comment]
SGTM. I think there are some other places that use this as well (headers frame?).

FYI, the way I found this was an edge case where there was a race between the connection processing incoming frames and being closed at about the same time.
