### ISSUE TITLE
Calling conn.SetIdleTimeout can hang if the other end closed the connection

### ISSUE THREAD

**Issue by ncdc** [docker/spdystream#63]
1. Establish SPDY connection between client and server
2. Close the client's connection
3. Attempt to call `conn.SetIdleTimeout()` on the server's connection

When 2 happens, the server connection's `Serve` goroutine ultimately exits, closing `closeChan`, which results in the `idleAwareFramer`'s `monitor` goroutine exiting as well. When you then try to call `conn.SetIdleTimeout`, it attempts to send to an unbuffered `setTimeoutChan`, but there is no other goroutine attempting to read from that channel (it used to be `monitor`, but that has since exited).

I've got a local branch that uses a lock to guard `SetIdleTimeout`, becoming a no-op if the connection has been closed. Does that sound like a good fix to you, @dmcgowan? If so, I'll prep a PR with a test case.

**Comment by dmcgowan** [comment]
That sounds like a reasonable fix, I would submit the PR and can see if the problem can be refactored to not use a lock but not really a concern either way.
