### ISSUE TITLE
./ws_test.go:27:15: too many arguments in call to conn.Serve

### ISSUE THREAD

**Issue by nim-nim** [docker/spdystream#71]
When building against github.com/gorilla/websocket version 1.2.0 (latest stable supported release, june 2017) unit tests fail with:

./ws_test.go:27:15: too many arguments in call to conn.Serve
./ws_test.go:27:46: undefined: spdystream.NoAuthHandler
./ws_test.go:53:19: too many arguments in call to spdyConn.Serve
        have (func(*spdystream.Stream), func(http.Header, uint8, uint32) bool)
        want (spdystream.StreamHandler)
./ws_test.go:78:19: too many arguments in call to spdyConn.Serve
./ws_test.go:78:50: undefined: spdystream.RejectAuthHandler
FAIL    github.com/docker/spdystream/ws [build failed]

**Comment by dmcgowan** [comment]
I would consider merging this as a contribution if you open a PR. Is this package being used somewhere that you ran into this?

**Comment by nim-nim** [comment]
Right now it's just running unit tests in all vendored packages to identify problems (after a few bad experiences vendoring without checking stuff)

Is this unit test supposed to run at all?

**Comment by dmcgowan** [comment]
Nothing is using this package https://godoc.org/github.com/docker/spdystream/ws. You are welcome to open a PR to fix the tests if you are going to use the package.
